# -------------------------------
# 基本配置
# -------------------------------
baseURL: https://yfc01.github.io  # 博客的基本 URL，用于生成链接
languageCode: zh-cn                # 默认语言为中文简体
title: yfc01's blog        # 博客的标题
theme: hugo-PaperMod               # 使用的主题，选择一个适合的 Hugo 主题
copyright: "© [2024 - 2025 yfc01's blog](https://yfc01.github.io)"

# -------------------------------
# 功能开关
# -------------------------------
enableInlineShortcodes: true       # 启用内联短代码功能（更灵活地嵌入 HTML）
enableEmoji: true                  # 支持 Emoji 表情，可以在文章中使用
enableRobotsTXT: true              # 允许搜索引擎爬取博客内容，影响 SEO
hasCJKLanguage: true               # 支持 CJK（中文、日文、韩文等），确保正确显示

# -------------------------------
# 构建设置
# -------------------------------
buildDrafts: false                 # 不构建草稿文章，草稿文章不会出现在最终构建中
buildFuture: false                 # 不构建未来的文章，只有已经发布的文章会被构建
buildExpired: false                # 不构建过期文章，只有有效期内的文章会被构建

# -------------------------------
# 分页设置
# -------------------------------
pagination:
  pagerSize: 10                    # 每页显示 10 篇文章，设置博客的分页大小

# -------------------------------
# 最小化设置
# -------------------------------
minify:
  disableXML: true                 # 禁用 XML 最小化，可能用于特定需求

# -------------------------------
# URL 形式设置
# -------------------------------
permalinks:
  post: "/:slug/"                 # 文章链接格式为 /:title/，使链接更友好

# -------------------------------
# 语言及本地化设置
# -------------------------------
defaultContentLanguage: zh          # 默认内容语言为中文
defaultContentLanguageInSubdir: false  # 默认语言内容不在子目录中

languages:
  zh:
    languageName: "中文"             # 语言名称，显示在语言选择器中
    weight: 1                        # 语言权重（排序时优先显示）
    taxonomies:
      category: categories           # 分类的名称
      tag: tags                     # 标签的名称
    params:
      profileMode:
        enabled: false              # 启用个人资料模式
        title:  ":-)"              # 个人资料标题
        subtitle: ""  # 个人资料副标题
        imageUrl: "img/active.jpg" # 个人资料图像 URL
        imageWidth: 150            # 图像宽度
        imageHeight: 150           # 图像高度
      homeInfoParams:
        # 首页的 profile 内容
        Title: "😊 Hi MyFriend"
        # 首页的 profile 内容
        Content: >
            欢迎来到我的博客！🌟
            <br>
            这里记录了我的学习心得、技术探索和生活点滴，希望与你一起分享和成长。
            如果你对 Web 开发、嵌入式编程或者 Hugo 博客有兴趣，欢迎交流讨论！🚀
            <br>
            **愿代码如诗，愿梦想闪光！**✨

    # ---------------------------
    # 导航菜单配置
    # ---------------------------
    menu:
      main:
        - name: 首页                # 菜单项名称
          pageRef: /                # 页面引用，指向首页
          weight: 1                  # 权重，决定菜单显示顺序
        - name: 目录
          pageRef: contents
          weight: 2
        - name: 分类
          pageRef: categories/
          weight: 3
        - name: 标签
          pageRef: tags/
          weight: 4
        - name: 归档
          pageRef: archives/
          weight: 10
        - name: 搜索
          pageRef: search/
          weight: 20
        - name: 关于
          pageRef: about/
          weight: 21

# -------------------------------
# 输出格式配置
# -------------------------------
outputs:
  home:
    - HTML                           # 首页输出 HTML 格式
    - RSS                            # 支持 RSS 输出，方便用户订阅
    - JSON                           # 支持 JSON 输出，用于 API 调用或其他用途

# -------------------------------
# 自定义参数配置
# -------------------------------
params:
  env: production                   # 设置当前环境为生产环境
  author: yfc01                     # 博主姓名，用于文章中显示
  defaultTheme: auto                 # 默认主题设置为自动，自动选择合适的主题（根据用户偏好）
  disableThemeToggle: false          # 启用主题切换功能，允许用户在深色/浅色主题之间切换
  DateFormat: "2006-01-02"          # 设置日期格式，控制文章日期的显示格式
  ShowShareButtons: true             # 启用分享按钮，方便读者将文章分享到社交平台
  ShowReadingTime: true              # 显示文章阅读时间，帮助读者了解阅读时长
  displayFullLangName: true          # 显示完整的语言名称，提升用户体验
  ShowPostNavLinks: true             # 显示文章的上下篇导航链接，方便用户浏览
  ShowBreadCrumbs: false            # 关闭面包屑导航，帮助用户知道当前页面在网站中的位置
  ShowCodeCopyButtons: true         # 启用代码复制按钮，方便用户复制文章中的代码
  hideFooter: false                 # 不隐藏页脚，保持页脚内容显示在页面底部
  ShowWordCounts: true              # 显示文章字数，帮助用户了解文章长度
  VisitCount: true                  # 启用访问计数功能，统计文章被访问的次数
  ShowLastMod: true                 # 显示最后修改时间，展示文章最近一次的更新时间
  ShowToc: true                     # 启用目录显示，帮助用户快速浏览文章结构
  TocOpen: false                    # 设置目录是否自动展开，默认关闭以提高可读性
  comments: true                    # 启用评论功能，允许读者对文章进行评论
  showbreadcrumbs: false            # 关闭显示当前路径，影响面包屑导航
  enableCopyright: true             # 启用文章版权声明，表明文章的版权归属
  licenseLink: "https://creativecommons.org/licenses/by-nc/4.0/"  # 设置版权声明链接，指向相应的许可证页面
  licenseName: "CC BY-NC 4.0"       # 设置版权许可证类型，表明文章采用的是"署名-非商业性使用 4.0 国际"许可证


  # -----------------------------
  # Giscus 评论配置
  # -----------------------------
  giscus:
    repo: "yfc01/yfc01.github.io"   # Giscus 评论系统关联的 GitHub 仓库
    repoId: "R_kgDOM33idg"           # GitHub 仓库 ID
    category: "Announcements"         # 讨论类别，影响评论的分类
    categoryId: "DIC_kwDOM33ids4Ci1Si" # 类别 ID
    mapping: "pathname"               # 评论关联的路径
    reactionsEnabled: "1"             # 启用反应功能，允许用户对评论进行反应
    emitMetadata: "0"                 # 是否发出元数据
    inputPosition: "bottom"           # 评论输入框位置
    lightTheme: "light"               # 轻主题
    darkTheme: "dark"                 # 暗主题
    lang: "zh-CN"                     # 评论语言
    crossorigin: "anonymous"           # 跨域设置

  # -----------------------------
  # 社交媒体图标配置
  # -----------------------------
  socialIcons:
    - name: github                    # 社交媒体名称
      url: "https://github.com/yfc01" # GitHub 个人主页链接
    - name: QQ
      url: "img/qq.jpg"               # QQ 图标链接
    - name: WeChat
      url: "img/wechat.jpg"           # 微信图标链接
    - name: email
      url: "mailto:2063454530@qq.com" # 邮件链接
    - name: notion
      url: "https://sugary-target-8ec.notion.site/HELLO-WORD-1287cee226d48045bf06e5084cd28e9b?pvs=4"

  # -----------------------------
  # 网站图标配置
  # -----------------------------
  assets:
    favicon: "img/active.jpg"         # 网站图标
    favicon16x16: "img/active.jpg"    # 16x16 网站图标
    favicon32x32: "img/active.jpg"    # 32x32 网站图标
    apple_touch_icon: "img/active.jpg" # Apple Touch 图标
    safari_pinned_tab: "img/active.jpg" # Safari 固定标签图标
    disableFingerprinting: true         # 禁用指纹识别

  # -----------------------------
  # 页面库配置（JavaScript 特效）
  # -----------------------------
  page:
    library:
      js:
        live2d_min1: "/js/live2d_min1.js"  # Live2D 特效脚本
        background_effects: "/js/background_effects.js" # 球体特效脚本
        anime_min: "/js/anime.min.js"        # 动画特效脚本
        fireworks: "/js/fireworks.js"        # 烟花特效脚本
        live2d_min2: "/js/live2d_min2.js"    # Live2D 特效脚本（备用）
        medium_zoom: "/js/medium_zoom.js"    # 图片放大效果

  # -------------------------------
  # 添加搜索参数，参考 https://fusejs.io/api/options.html
  # -------------------------------
  fuseOpts:
    isCaseSensitive: false              # 是否区分大小写，设置为 false 使搜索不区分大小写
    includeMatches: true                 # 是否包括匹配项，设置为 true 表示在结果中包含匹配的部分
    shouldSort: true                     # 是否对结果进行排序，设置为 true 表示按匹配程度对结果排序
    location: 0                          # 指定搜索位置的偏移量，0 表示从开头开始搜索
    distance: 1000                       # 指定搜索的距离，较大的值会允许更远的匹配，默认值为 100
    threshold: 0.1                       # 搜索匹配的阈值，值越小越严格，范围从 0 到 1，0 表示完全匹配，1 表示不匹配
    minMatchCharLength: 0                # 最小匹配字符长度，设置为 0 表示可以匹配空字符串
    keys: ["title", "permalink", "summary", "content"] # 指定搜索的字段，可以是文章的标题、永久链接、摘要和内容


# -------------------------------
# Markdown 渲染设置
# -------------------------------
markup:
  goldmark:
    renderer:
      unsafe: true                      # 允许 HTML 的渲染，增强 Markdown 功能
  highlight:
    noClasses: false                    # 不使用类的样式，保持样式兼容性
    codeFences: true                    # 支持代码块的高亮显示
    guessSyntax: true                   # 自动猜测代码语法
    lineNos: true                       # 显示代码行号
    lineNumbersInTable: true            # 在表格中显示行号
    tabWidth: 4                         # 设置 Tab 键宽度
    hl_Lines: ""                        # 需要高亮的行，使用逗号分隔
    wrapCode: true                      # 是否换行显示代码

# -------------------------------
# 隐私设置
# -------------------------------
privacy:
  vimeo:
    disabled: false                     # 是否禁用 Vimeo
    simple: true                       # 是否使用简单模式
  twitter:
    disabled: false                     # 是否禁用 Twitter
    enableDNT: true                    # 启用 Do Not Track
    simple: true                       # 是否使用简单模式
  instagram:
    disabled: false                     # 是否禁用 Instagram
    simple: true                       # 是否使用简单模式
  youtube:
    disabled: false                     # 是否禁用 YouTube
    privacyEnhanced: true               # 启用隐私增强模式

# -------------------------------
# 服务设置
# -------------------------------
services:
  instagram:
    disableInlineCSS: true             # 是否禁用 Instagram 的内联 CSS
  twitter:
    disableInlineCSS: true              # 是否禁用 Twitter 的内联 CSS
